[package]
name = "algo_full"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

algo_find = { path = "find" }
algo_sort = { path = "sort" }